version: '3.7'

services:
  mariadb:
    image: docker.io/library/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_USER: "exampleuser"
      MYSQL_PASSWORD: "123"
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - devnetwork

  phpmyadmin:
    image: docker.io/library/phpmyadmin:latest
    environment:
      PMA_HOST: mariadb 
      PMA_PORT: 3306
    depends_on:
      - mariadb
    ports:
      - "8040:80"
    networks:
      - devnetwork

networks:
  devnetwork:
    driver: bridge

volumes:
  mariadb_data:
